draw_set_font(font_about);
if(global.about == 1)
{
	draw_text(x,y,@"NATE LIVES IN THE MIDDLE OF NOWHERE
	(ALSO KNOWN AS RURAL OHIO). WHEN NOT
	CODING INCOMPREHENSIBLE GAMES, NATE
	LIKES TO PLAY OTHER GAMES AND EAT DONUTS,
	SPEND TIME WITH FAMILY WHILE EATING
	DONUTS, HAVE DEEP CONVERSATIONS ABOUT
	DONUTS, AND TRAVEL TO FIND MORE DONUTS.
	NATE ALSO LIKES TO INSERT THE WORD
	''PINEAPPLE'' INTO AS MANY SENTENCES AS
	POSSIBLE, PREFERABLY WHERE IT DOESN'T FIT.");
}
else if(global.about == 2)
{
	draw_text(x,y,@"JORDAN ALSO LIVES IN THE MIDDLE OF
	NOWHERE (ALSO KNOWN AS RURAL OHIO).
	WHEN NOT PIECING TOGETHER MEDIOCRE ART,
	JORDAN SPENDS HIS TIME READING AND
	WRITING (''ABOUT PINEAPPLES''), ENJOYING THE
	COMPANY OF HIS FAMILY (''AND PINEAPPLES''),
	PLAYING TABLETOP AND VIDEO GAMES (''USING
	PINEAPPLES''), OGLING AT CUTE GUYS (''DRESSED
	AS PINEAPPLES''), AND LOOKING FOR ADVENTURES
	(''SAY PINEAPPLE ONE MORE TIME AND I KILL
	YOU NATE!'').");
}
draw_set_font(font_all);