// Initialise the global array that allows the lookup of the depth of a given object
// GM2.0 does not have a depth on objects so on import from 1.x a global array is created
// NOTE: MacroExpansion is used to insert the array initialisation at import time
gml_pragma( "global", "__global_object_depths()");

// insert the generated arrays here
global.__objectDepths[0] = -1; // obj_text_atlas_p2
global.__objectDepths[1] = -1; // obj_text_atlas_p1
global.__objectDepths[2] = 0; // obj_splash_altas_left
global.__objectDepths[3] = 0; // obj_splash_atlas_right
global.__objectDepths[4] = -100; // obj_filter_biz
global.__objectDepths[5] = -7; // obj_mm_token
global.__objectDepths[6] = 0; // obj_button_switch
global.__objectDepths[7] = -1; // obj_skin_large
global.__objectDepths[8] = -7; // obj_leaf
global.__objectDepths[9] = -1; // obj_selector_bg
global.__objectDepths[10] = 0; // obj_mm_bg_setup
global.__objectDepths[11] = 2; // obj_selected_skin
global.__objectDepths[12] = 0; // obj_profile_setup
global.__objectDepths[13] = -100; // obj_filter_eod
global.__objectDepths[14] = 2; // obj_current_skin
global.__objectDepths[15] = -1; // obj_arrow
global.__objectDepths[16] = 0; // obj_menu_effect_spawn
global.__objectDepths[17] = -4; // obj_scroll_mimi
global.__objectDepths[18] = -8; // obj_button_google
global.__objectDepths[19] = 3; // obj_selector_skin
global.__objectDepths[20] = 0; // obj_selector_cp
global.__objectDepths[21] = -2; // obj_menu_light
global.__objectDepths[22] = -11; // obj_scroll_big
global.__objectDepths[23] = 0; // obj_selector_cp2
global.__objectDepths[24] = 0; // obj_selector_cp3
global.__objectDepths[25] = -1; // obj_menu_darkness
global.__objectDepths[26] = -13; // obj_medal_level
global.__objectDepths[27] = 0; // obj_selector_cp1
global.__objectDepths[28] = -10; // obj_chapter_tab
global.__objectDepths[29] = 0; // obj_selector_cp4
global.__objectDepths[30] = -17; // obj_endmode_score
global.__objectDepths[31] = -13; // obj_lvl_divider
global.__objectDepths[32] = -13; // obj_challenge_wreath
global.__objectDepths[33] = -12; // obj_selector_level
global.__objectDepths[34] = -20; // obj_chapter_tab_sm
global.__objectDepths[35] = -1; // obj_menu_bleam
global.__objectDepths[36] = -16; // obj_scroll
global.__objectDepths[37] = -17; // obj_button_bizarro
global.__objectDepths[38] = -17; // obj_button_menu
global.__objectDepths[39] = -17; // obj_button_achiev
global.__objectDepths[40] = -14; // obj_nav_prof
global.__objectDepths[41] = -13; // obj_nav_main
global.__objectDepths[42] = -12; // obj_nav_flag
global.__objectDepths[43] = -17; // obj_button_play
global.__objectDepths[44] = -17; // obj_button_challenge
global.__objectDepths[45] = -17; // obj_button_endless
global.__objectDepths[46] = -14; // obj_nav_play
global.__objectDepths[47] = -17; // obj_button_fool
global.__objectDepths[48] = -17; // obj_button_eod
global.__objectDepths[49] = -5; // obj_button_purchase
global.__objectDepths[50] = -17; // obj_button_chapter
global.__objectDepths[51] = -17; // obj_button_next_level
global.__objectDepths[52] = -17; // obj_button_profile
global.__objectDepths[53] = -17; // obj_button_tutorial
global.__objectDepths[54] = -14; // obj_gameover_cpt
global.__objectDepths[55] = -11; // obj_scroll_gameover
global.__objectDepths[56] = -15; // obj_gameover_wreath
global.__objectDepths[57] = -17; // obj_button_retry
global.__objectDepths[58] = -25; // obj_text_timer
global.__objectDepths[59] = -15; // obj_text_lvlunlock
global.__objectDepths[60] = -13; // obj_unlocked_current
global.__objectDepths[61] = -5; // obj_button_select
global.__objectDepths[62] = -13; // obj_unlocked_box
global.__objectDepths[63] = -15; // obj_unlocks_senor
global.__objectDepths[64] = -12; // obj_gv_level
global.__objectDepths[65] = -15; // obj_text_cptunlock
global.__objectDepths[66] = -16; // obj_cptunlock_mini
global.__objectDepths[67] = 0; // obj_gameover_setup
global.__objectDepths[68] = -20; // obj_watermark
global.__objectDepths[69] = -13; // obj_gameover_time
global.__objectDepths[70] = -30; // obj_darkness
global.__objectDepths[71] = 0; // obj_windchange
global.__objectDepths[72] = -29; // obj_rain
global.__objectDepths[73] = 0; // obj_rain_spawn
global.__objectDepths[74] = -1; // obj_glint
global.__objectDepths[75] = -1; // obj_burn
global.__objectDepths[76] = -20; // obj_vine_right
global.__objectDepths[77] = 1; // obj_ghost
global.__objectDepths[78] = -10; // obj_darkness_cloud
global.__objectDepths[79] = -1; // obj_sunbleam
global.__objectDepths[80] = 3; // obj_halo_blue
global.__objectDepths[81] = -20; // obj_vine_left
global.__objectDepths[82] = -13; // obj_gameover_sphee
global.__objectDepths[83] = 3; // obj_halo_black
global.__objectDepths[84] = 3; // obj_halo_green
global.__objectDepths[85] = -10; // obj_leaf_lvl
global.__objectDepths[86] = -100; // obj_sun_affect
global.__objectDepths[87] = 3; // obj_halo_red
global.__objectDepths[88] = 3; // obj_halo_white
global.__objectDepths[89] = -20; // obj_swipe_senor
global.__objectDepths[90] = -20; // obj_swipe_senor_cone
global.__objectDepths[91] = -3; // obj_sequence_current
global.__objectDepths[92] = -3; // obj_sequence_current_sm
global.__objectDepths[93] = -26; // obj_timer_medal
global.__objectDepths[94] = -4; // obj_sequence_glow
global.__objectDepths[95] = 0; // obj_sequence_upcoming
global.__objectDepths[96] = 3; // obj_halo_yellow
global.__objectDepths[97] = -19; // obj_swipe_glow
global.__objectDepths[98] = -1; // obj_hud_bar
global.__objectDepths[99] = -26; // obj_timer_medal_left
global.__objectDepths[100] = -24; // obj_timer_bar_outline
global.__objectDepths[101] = -4; // obj_text_remaining
global.__objectDepths[102] = -20; // obj_swipe_senor_wall
global.__objectDepths[103] = -26; // obj_timer_medal_right
global.__objectDepths[104] = -25; // obj_timer_bar
global.__objectDepths[105] = -2; // obj_scored_drop
global.__objectDepths[106] = -14; // obj_text_right
global.__objectDepths[107] = 1; // obj_ledge
global.__objectDepths[108] = 0; // obj_token_crack
global.__objectDepths[109] = 1; // obj_drop
global.__objectDepths[110] = -11; // obj_track_color
global.__objectDepths[111] = 0; // obj_atlas
global.__objectDepths[112] = -13; // obj_track_cover
global.__objectDepths[113] = 0; // obj_drop_spawn
global.__objectDepths[114] = -1; // obj_token_broken_left
global.__objectDepths[115] = 0; // obj_lvl_setup
global.__objectDepths[116] = 0; // obj_sphee
global.__objectDepths[117] = -14; // obj_text_left
global.__objectDepths[118] = -12; // obj_track_sphee
global.__objectDepths[119] = -29; // obj_red_fade_right
global.__objectDepths[120] = -1; // obj_token_broken_right
global.__objectDepths[121] = 0; // obj_spawn_meteor
global.__objectDepths[122] = 0; // obj_eod_swipe_wall
global.__objectDepths[123] = 4; // obj_bg_fog
global.__objectDepths[124] = -24; // obj_text_score
global.__objectDepths[125] = 0; // obj_sphee_dummy
global.__objectDepths[126] = 6; // obj_meteor
global.__objectDepths[127] = 3; // obj_meteor_split
global.__objectDepths[128] = 0; // obj_eod_swipe_senor
global.__objectDepths[129] = -22; // obj_track_sphee_dummy
global.__objectDepths[130] = -29; // obj_red_fade_left
global.__objectDepths[131] = 0; // obj_meteor_spawn_mini
global.__objectDepths[132] = 0; // obj_eod_setup
global.__objectDepths[133] = -25; // obj_eod_timer_bar
global.__objectDepths[134] = -25; // obj_fool_timer_bar
global.__objectDepths[135] = 0; // obj_fool_setup
global.__objectDepths[136] = 0; // obj_drop_spawn_biz
global.__objectDepths[137] = -3; // obj_sequence_current_fool
global.__objectDepths[138] = 1; // obj_drop_biz
global.__objectDepths[139] = 1; // obj_drop_fool
global.__objectDepths[140] = 0; // obj_spawn_drop_fool
global.__objectDepths[141] = 6; // obj_meteor_mini
global.__objectDepths[142] = -30; // obj_the_cat
global.__objectDepths[143] = 1; // obj_drop_tutorial
global.__objectDepths[144] = -5; // obj_tutorial_swipe_pattern
global.__objectDepths[145] = 1; // obj_cam
global.__objectDepths[146] = -31; // obj_cat_retalk
global.__objectDepths[147] = -30; // obj_speak_bubble
global.__objectDepths[148] = -15; // obj_pause_senor
global.__objectDepths[149] = 0; // obj_drop_spawn_tutorial
global.__objectDepths[150] = 0; // obj_tutorial_setup
global.__objectDepths[151] = 0; // obj_inital
global.__objectDepths[152] = 0; // obj_sphee_tutorial
global.__objectDepths[153] = -100; // obj_fade_black
global.__objectDepths[154] = 0; // obj_backbutton_senor
global.__objectDepths[155] = -5; // obj_tutorial_swipe_end
global.__objectDepths[156] = 0; // obj_con_rm_jfg
global.__objectDepths[157] = -22; // obj_track_sphee_tutorial


global.__objectNames[0] = "obj_text_atlas_p2";
global.__objectNames[1] = "obj_text_atlas_p1";
global.__objectNames[2] = "obj_splash_altas_left";
global.__objectNames[3] = "obj_splash_atlas_right";
global.__objectNames[4] = "obj_filter_biz";
global.__objectNames[5] = "obj_mm_token";
global.__objectNames[6] = "obj_button_switch";
global.__objectNames[7] = "obj_skin_large";
global.__objectNames[8] = "obj_leaf";
global.__objectNames[9] = "obj_selector_bg";
global.__objectNames[10] = "obj_mm_bg_setup";
global.__objectNames[11] = "obj_selected_skin";
global.__objectNames[12] = "obj_profile_setup";
global.__objectNames[13] = "obj_filter_eod";
global.__objectNames[14] = "obj_current_skin";
global.__objectNames[15] = "obj_arrow";
global.__objectNames[16] = "obj_menu_effect_spawn";
global.__objectNames[17] = "obj_scroll_mimi";
global.__objectNames[18] = "obj_button_google";
global.__objectNames[19] = "obj_selector_skin";
global.__objectNames[20] = "obj_selector_cp";
global.__objectNames[21] = "obj_menu_light";
global.__objectNames[22] = "obj_scroll_big";
global.__objectNames[23] = "obj_selector_cp2";
global.__objectNames[24] = "obj_selector_cp3";
global.__objectNames[25] = "obj_menu_darkness";
global.__objectNames[26] = "obj_medal_level";
global.__objectNames[27] = "obj_selector_cp1";
global.__objectNames[28] = "obj_chapter_tab";
global.__objectNames[29] = "obj_selector_cp4";
global.__objectNames[30] = "obj_endmode_score";
global.__objectNames[31] = "obj_lvl_divider";
global.__objectNames[32] = "obj_challenge_wreath";
global.__objectNames[33] = "obj_selector_level";
global.__objectNames[34] = "obj_chapter_tab_sm";
global.__objectNames[35] = "obj_menu_bleam";
global.__objectNames[36] = "obj_scroll";
global.__objectNames[37] = "obj_button_bizarro";
global.__objectNames[38] = "obj_button_menu";
global.__objectNames[39] = "obj_button_achiev";
global.__objectNames[40] = "obj_nav_prof";
global.__objectNames[41] = "obj_nav_main";
global.__objectNames[42] = "obj_nav_flag";
global.__objectNames[43] = "obj_button_play";
global.__objectNames[44] = "obj_button_challenge";
global.__objectNames[45] = "obj_button_endless";
global.__objectNames[46] = "obj_nav_play";
global.__objectNames[47] = "obj_button_fool";
global.__objectNames[48] = "obj_button_eod";
global.__objectNames[49] = "obj_button_purchase";
global.__objectNames[50] = "obj_button_chapter";
global.__objectNames[51] = "obj_button_next_level";
global.__objectNames[52] = "obj_button_profile";
global.__objectNames[53] = "obj_button_tutorial";
global.__objectNames[54] = "obj_gameover_cpt";
global.__objectNames[55] = "obj_scroll_gameover";
global.__objectNames[56] = "obj_gameover_wreath";
global.__objectNames[57] = "obj_button_retry";
global.__objectNames[58] = "obj_text_timer";
global.__objectNames[59] = "obj_text_lvlunlock";
global.__objectNames[60] = "obj_unlocked_current";
global.__objectNames[61] = "obj_button_select";
global.__objectNames[62] = "obj_unlocked_box";
global.__objectNames[63] = "obj_unlocks_senor";
global.__objectNames[64] = "obj_gv_level";
global.__objectNames[65] = "obj_text_cptunlock";
global.__objectNames[66] = "obj_cptunlock_mini";
global.__objectNames[67] = "obj_gameover_setup";
global.__objectNames[68] = "obj_watermark";
global.__objectNames[69] = "obj_gameover_time";
global.__objectNames[70] = "obj_darkness";
global.__objectNames[71] = "obj_windchange";
global.__objectNames[72] = "obj_rain";
global.__objectNames[73] = "obj_rain_spawn";
global.__objectNames[74] = "obj_glint";
global.__objectNames[75] = "obj_burn";
global.__objectNames[76] = "obj_vine_right";
global.__objectNames[77] = "obj_ghost";
global.__objectNames[78] = "obj_darkness_cloud";
global.__objectNames[79] = "obj_sunbleam";
global.__objectNames[80] = "obj_halo_blue";
global.__objectNames[81] = "obj_vine_left";
global.__objectNames[82] = "obj_gameover_sphee";
global.__objectNames[83] = "obj_halo_black";
global.__objectNames[84] = "obj_halo_green";
global.__objectNames[85] = "obj_leaf_lvl";
global.__objectNames[86] = "obj_sun_affect";
global.__objectNames[87] = "obj_halo_red";
global.__objectNames[88] = "obj_halo_white";
global.__objectNames[89] = "obj_swipe_senor";
global.__objectNames[90] = "obj_swipe_senor_cone";
global.__objectNames[91] = "obj_sequence_current";
global.__objectNames[92] = "obj_sequence_current_sm";
global.__objectNames[93] = "obj_timer_medal";
global.__objectNames[94] = "obj_sequence_glow";
global.__objectNames[95] = "obj_sequence_upcoming";
global.__objectNames[96] = "obj_halo_yellow";
global.__objectNames[97] = "obj_swipe_glow";
global.__objectNames[98] = "obj_hud_bar";
global.__objectNames[99] = "obj_timer_medal_left";
global.__objectNames[100] = "obj_timer_bar_outline";
global.__objectNames[101] = "obj_text_remaining";
global.__objectNames[102] = "obj_swipe_senor_wall";
global.__objectNames[103] = "obj_timer_medal_right";
global.__objectNames[104] = "obj_timer_bar";
global.__objectNames[105] = "obj_scored_drop";
global.__objectNames[106] = "obj_text_right";
global.__objectNames[107] = "obj_ledge";
global.__objectNames[108] = "obj_token_crack";
global.__objectNames[109] = "obj_drop";
global.__objectNames[110] = "obj_track_color";
global.__objectNames[111] = "obj_atlas";
global.__objectNames[112] = "obj_track_cover";
global.__objectNames[113] = "obj_drop_spawn";
global.__objectNames[114] = "obj_token_broken_left";
global.__objectNames[115] = "obj_lvl_setup";
global.__objectNames[116] = "obj_sphee";
global.__objectNames[117] = "obj_text_left";
global.__objectNames[118] = "obj_track_sphee";
global.__objectNames[119] = "obj_red_fade_right";
global.__objectNames[120] = "obj_token_broken_right";
global.__objectNames[121] = "obj_spawn_meteor";
global.__objectNames[122] = "obj_eod_swipe_wall";
global.__objectNames[123] = "obj_bg_fog";
global.__objectNames[124] = "obj_text_score";
global.__objectNames[125] = "obj_sphee_dummy";
global.__objectNames[126] = "obj_meteor";
global.__objectNames[127] = "obj_meteor_split";
global.__objectNames[128] = "obj_eod_swipe_senor";
global.__objectNames[129] = "obj_track_sphee_dummy";
global.__objectNames[130] = "obj_red_fade_left";
global.__objectNames[131] = "obj_meteor_spawn_mini";
global.__objectNames[132] = "obj_eod_setup";
global.__objectNames[133] = "obj_eod_timer_bar";
global.__objectNames[134] = "obj_fool_timer_bar";
global.__objectNames[135] = "obj_fool_setup";
global.__objectNames[136] = "obj_drop_spawn_biz";
global.__objectNames[137] = "obj_sequence_current_fool";
global.__objectNames[138] = "obj_drop_biz";
global.__objectNames[139] = "obj_drop_fool";
global.__objectNames[140] = "obj_spawn_drop_fool";
global.__objectNames[141] = "obj_meteor_mini";
global.__objectNames[142] = "obj_the_cat";
global.__objectNames[143] = "obj_drop_tutorial";
global.__objectNames[144] = "obj_tutorial_swipe_pattern";
global.__objectNames[145] = "obj_cam";
global.__objectNames[146] = "obj_cat_retalk";
global.__objectNames[147] = "obj_speak_bubble";
global.__objectNames[148] = "obj_pause_senor";
global.__objectNames[149] = "obj_drop_spawn_tutorial";
global.__objectNames[150] = "obj_tutorial_setup";
global.__objectNames[151] = "obj_inital";
global.__objectNames[152] = "obj_sphee_tutorial";
global.__objectNames[153] = "obj_fade_black";
global.__objectNames[154] = "obj_backbutton_senor";
global.__objectNames[155] = "obj_tutorial_swipe_end";
global.__objectNames[156] = "obj_con_rm_jfg";
global.__objectNames[157] = "obj_track_sphee_tutorial";


// create another array that has the correct entries
var len = array_length_1d(global.__objectDepths);
global.__objectID2Depth = [];
for( var i=0; i<len; ++i ) {
	var objID = asset_get_index( global.__objectNames[i] );
	if (objID >= 0) {
		global.__objectID2Depth[ objID ] = global.__objectDepths[i];
	} // end if
} // end for