draw_set_font(font_about);
draw_text(x,y,@"THIS GAME WAS DESIGNED USING GAMEMAKER STUDIO
(YOYO GAMES LTD.), GIMP (GNU IMAGE MANIPULATION
PROGRAM), AND SPINE (ESOTERIC SOFTWARE). THE FONT
USED IN THIS GAME IS CAPITALIS MINIMALIS BY UWE
BORCHERT (SIL OPEN FONT LICENSE) AND IN-GAME
SOUND EFFECTS BY SOUNDJAY.COM. MUSIC: ROYALTY
FREE MUSIC FROM BENSOUND (''NOVEMBER'', ''EPIC'', &
''ENIGMATIC'') AND ''LIFE CLOCK'' BY WILLIAM USHER.
SPECIAL THANKS TO OUR WONDERFUL FAMILY (AND
PINEAPPLES EVERYWHERE) FOR PUTTING UP WITH US,
OFFERING OPINIONS, SUGGESTIONS, AND PLAYTESTING.");
draw_set_font(font_all);