if(alarm_get(1) > 1)
{
	draw_text_color(x,y,@"DISCLAIMER!
	
	THIS GAME CONTAINS PURCHASABLE CONTENT AND ADS.
	
	ALL PURCHASABLE CONTENT CAN ALSO BE UNLOCKED
	FOR FREE THROUGH GAMEPLAY.
	
	IT IS OUR HOPE THAT THE ADS USED IN THIS GAME
	ARE NOT INTRUSIVE OR DISRUPTIVE. MANDATORY ADS CAN BE
	REMOVED BY SPENDING $2.00 OR MORE ON PURCHASABLE
	CONTENT OR VIA DONATION.",c_white,c_white,c_white,c_white,1);
}
else if(alarm_get(1) < 2)
{
	draw_text_color(x,y,@"DISCLAIMER!
	
	THIS GAME CONTAINS PURCHASABLE CONTENT AND ADS.
	
	ALL PURCHASABLE CONTENT CAN ALSO BE UNLOCKED
	FOR FREE THROUGH GAMEPLAY.
	
	IT IS OUR HOPE THAT THE ADS USED IN THIS GAME
	ARE NOT INTRUSIVE OR DISRUPTIVE. MANDATORY ADS CAN BE
	REMOVED BY SPENDING $2.00 OR MORE ON PURCHASABLE
	CONTENT OR VIA DONATION.",c_white,c_white,c_white,c_white,image_alpha);
}
draw_text_color(x,y + 300,"DOUBLE TAP TO SKIP",c_white,c_white,c_white,c_white,image_alpha);