draw_set_font(font_about);
if(y == 135)
{
	draw_text(x,y,@"ENJOYING THE GAME? HAVE
	COMPLAINTS TO MAKE? TOO
	TALKATIVE FOR YOUR OWN GOOD?
	LEAVE US YOUR HONEST REVIEW!");
	draw_text(x+1,y+1,@"ENJOYING THE GAME? HAVE
	COMPLAINTS TO MAKE? TOO
	TALKATIVE FOR YOUR OWN GOOD?
	LEAVE US YOUR HONEST REVIEW!");
}
else if(y == 350)
{
	draw_text(x,y,@"HAVE MONEY TO WASTE? IF SO,
	DONATE TO US SO WE CAN MAKE
	MORE WEIRD GAMES!");
	draw_text(x+1,y+1,@"HAVE MONEY TO WASTE? IF SO,
	DONATE TO US SO WE CAN MAKE
	MORE WEIRD GAMES!");
}
else if(y == 595)
{
	draw_text(x,y,@"THIS GAME MAKING NO SENSE TO
	YOU? FOLLOW US ON FACEBOOK AND
	TWITTER FOR MORE CONFUSING
	CONTENT AND NONSENSICAL NEWS!");
	draw_text(x+1,y+1,@"THIS GAME MAKING NO SENSE TO
	YOU? FOLLOW US ON FACEBOOK AND
	TWITTER FOR MORE CONFUSING
	CONTENT AND NONSENSICAL NEWS!");
}
draw_set_font(font_all);